"""
We only keep products that we are going to predict
 'Avo & Hal Muffin',
 'Avo, Egg & Bacon',
 'Avo, Feta & Tom',
 'Avocado on Toast',
 'Bacon',
 'Bacon Bap',
 'Bacon Egg Brioch',
 'Bacon Waffle',
 'Baked Beans',
 'Baked Beans JP',
 'Bean Soldiers',
 'Big Breakfast',
 'Black Pudding',
 'Breakfast Hash',
 'Breakfast Muffin',
 'Breakfast Wrap',
 'Buttd Mushrooms',
 'Cheese & Bean JP',
 'Cheese JP',
 'Chick Flatbread',
 'Chicken Club',
 'Chilli Carne JP',
 'Egg Bacon Brioch',
 'Egg Bap',
 'Extra Beans',
 'F.Eggs on Toast',
 'Festive Stack',
 'Fried Egg',
 'Hash Brown',
 'Hash Brown Bites',
 'Little Avo Toast',
 'Little Bean Toas',
 'Little Egg Toast',
 'Ltle Bfast Bacon',
 'Ltle Bfast Saus',
 'Mini Hash Browns',
 'P.Eggs on Toast',
 'Poached Egg',
 'Posh Beans',
 'Roll & Butter ',
 'S.Eggs on Toast',
 'Sausage',
 'Sausage Bap',
 'Scrambled Egg',
 'Streaky Bacon',
 'Tattie Scone',
 'The Breakfast',
 'Toasted Teacake',
 'Tuna JP',
 'Tuna Mayo Mix',
 'Tuna Melt Panini',
 'Tuna Panini',
 'Tuna Toastie',
 'Veg Sausage Bap',
 'Vegan Breakfast',
 'Vegan Sausage',
 'Veggie Bap',
 'Veggie Breakfast',
 'Bakery',
 'White Toast Bread',
 'Brown Toast Bread',
 'Porridge',
 'Sourdough Toast Bread',
 'Multiseed Toast Bread',
"""
import pandas as pd

recipes = pd.DataFrame([
    {"product": "Avo & Hal Muffin", "ingredient": "English Muffin","quantity": 1, "unit": "pieces"},
    {"product": "Avo & Hal Muffin", "ingredient": "Halloumi","quantity": 2, "unit": "slices"},
    {"product": "Avo & Hal Muffin", "ingredient": "Avocado","quantity": 0.5, "unit": "pieces"},
    {"product": "Avo & Hal Muffin", "ingredient": "Lime","quantity":0.25, "unit": "pieces"},
    {"product": "Avo & Hal Muffin", "ingredient": "Sweet Chilli Jam","quantity":15, "unit": "grams"},
    {"product": "Avo, Egg & Bacon", "ingredient": "Sourdough Loaf","quantity":1, "unit": "slices"},
    {"product": "Avo, Egg & Bacon", "ingredient": "Avocado","quantity":0.5, "unit": "pieces"},
    {"product": "Avo, Egg & Bacon", "ingredient": "Lime","quantity":0.25, "unit": "pieces"},
    {"product": "Avo, Egg & Bacon", "ingredient": "Unsmoked Streaky Bacon","quantity":2, "unit": "rashers"},
    {"product": "Avo, Egg & Bacon", "ingredient": "Fried Egg","quantity":1, "unit": "pieces"},
    {"product": "Avo, Egg & Bacon", "ingredient": "Crushed Chillies","quantity":1, "unit": "grams"},
    {"product": "Avo, Egg & Bacon", "ingredient": "Wild Rocket","quantity":5, "unit": "grams"},
    {"product": "Avo, Feta & Tom", "ingredient": "Sourdough Loaf", "quantity": 1, "unit": "slices"},
    {"product": "Avo, Feta & Tom", "ingredient": "Avocado", "quantity": 0.5, "unit": "pieces"},
    {"product": "Avo, Feta & Tom", "ingredient": "Lime", "quantity": 0.25, "unit": "pieces"},
    {"product": "Avo, Feta & Tom", "ingredient": "Sun Dried Tomatoes", "quantity": 30, "unit": "grams"},
    {"product": "Avo, Feta & Tom", "ingredient": "Feta Cheese", "quantity": 25, "unit": "grams"},
    {"product": "Avo, Feta & Tom", "ingredient": "Vinegar", "quantity": 10, "unit": "grams"},
    {"product": "Avocado on Toast", "ingredient": "Sourdough Loaf", "quantity": 1, "unit": "slices"},
    {"product": "Avocado on Toast", "ingredient": "Avocado", "quantity": 0.5, "unit": "pieces"},
    {"product": "Avocado on Toast", "ingredient": "Tomato", "quantity": 0.5, "unit": "pieces"},
    {"product": "Avocado on Toast", "ingredient": "Crushed Chillies", "quantity": 1, "unit": "grams"},
    {"product": "Bacon", "ingredient": "Back Bacon", "quantity": 1, "unit": "rashers"},
    {"product": "Bacon Bap", "ingredient": "Back Bacon", "quantity": 2, "unit": "rashers"},
    {"product": "Bacon Bap", "ingredient": "Large White Bap", "quantity": 1, "unit": "pieces"},
    {"product": "Bacon Bap", "ingredient": "Unsalted Butter", "quantity": 10, "unit": "grams"},
    {"product": "Bacon Egg Brioch", "ingredient": "Brioche Bun", "quantity": 1, "unit": "pieces"},
    {"product": "Bacon Egg Brioch", "ingredient": "Fried Egg", "quantity": 1, "unit": "pieces"},
    {"product": "Bacon Egg Brioch", "ingredient": "Unsmoked Streaky Bacon", "quantity": 2, "unit": "rashers"},
    {"product": "Bacon Egg Brioch", "ingredient": "Wild Rocket", "quantity": 5, "unit": "grams"},
    {"product": "Bacon Egg Brioch", "ingredient": "Sweet Chilli Jam", "quantity": 10, "unit": "grams"},
    {"product": "Bacon Egg Brioch", "ingredient": "Coriander", "quantity": 2, "unit": "grams"},
    {"product": "Bacon Egg Brioch", "ingredient": "Soft Cheese", "quantity": 35, "unit": "grams"},
    {"product": "Bacon Egg Brioch", "ingredient": "Crushed Chillies", "quantity": 0.5, "unit": "grams"},
    {"product": "Bacon Waffle", "ingredient": "Belgian Sugar Waffles", "quantity": 2, "unit": "pieces"},
    {"product": "Bacon Waffle", "ingredient": "Unsmoked Streaky Bacon", "quantity": 3, "unit": "rashers"},
    {"product": "Bacon Waffle", "ingredient": "Maple Syrup", "quantity":10, "unit": "grams"},
    {"product": "Baked Beans", "ingredient": "Baked Beans", "quantity":80, "unit": "grams"},
    {"product": "Baked Beans JP", "ingredient": "Baked Beans", "quantity":80, "unit": "grams"},
    {"product": "Baked Beans JP", "ingredient": "Baking Potato", "quantity":1, "unit": "pieces"},
    {"product": "Baked Beans JP", "ingredient": "Babyleaf Salad", "quantity":15, "unit": "grams"},
    {"product": "Baked Beans JP", "ingredient": "Cherry Tomatoes", "quantity":1, "unit": "pieces"},
    {"product": "Bean Soldiers", "ingredient": "50/50 Whole Bread", "quantity":1, "unit": "slices"},
    {"product": "Bean Soldiers", "ingredient": "Baked Beans", "quantity":80, "unit": "grams"},
    {"product": "Big Breakfast", "ingredient": "Baked Beans", "quantity":80, "unit": "grams"},
    {"product": "Big Breakfast", "ingredient": "Pork Sausage", "quantity":2, "unit": "pieces"},
    {"product": "Big Breakfast", "ingredient": "Back Bacon", "quantity":2, "unit": "rashers"},
    {"product": "Big Breakfast", "ingredient": "Fried Egg", "quantity":2, "unit": "pieces"},
    {"product": "Big Breakfast", "ingredient": "Hash Brown", "quantity":3, "unit": "pieces"},
    {"product": "Big Breakfast", "ingredient": "Tattie Scone", "quantity":1, "unit": "pieces"},
    {"product": "Black Pudding", "ingredient": "Black Pudding", "quantity":1, "unit": "pieces"},
    {"product": "Breakfast Hash", "ingredient": "Hash Brown Bites", "quantity":150, "unit": "grams"},
    {"product": "Breakfast Hash", "ingredient": "Red Pepper", "quantity":0.5, "unit": "pieces"},
    {"product": "Breakfast Hash", "ingredient": "Spring Onion", "quantity":10, "unit": "grams"},
    {"product": "Breakfast Hash", "ingredient": "Fried Egg", "quantity":1, "unit": "pieces"},
    {"product": "Breakfast Hash", "ingredient": "Mixed Baked Beans", "quantity":0.5, "unit": "tin"},
    {"product": "Breakfast Hash", "ingredient": "Smoked Paprika", "quantity":2, "unit": "grams"},
    {"product": "Breakfast Muffin", "ingredient": "English Muffin", "quantity":1, "unit": "pieces"},
    {"product": "Breakfast Muffin", "ingredient": "Pork Sausage", "quantity":1, "unit": "pieces"},
    {"product": "Breakfast Muffin", "ingredient": "Fried Egg", "quantity":1, "unit": "pieces"},
    {"product": "Breakfast Muffin", "ingredient": "Mild Cheese", "quantity":1, "unit": "slices"},
    {"product": "Breakfast Wrap", "ingredient": "Tortilla Wrap", "quantity":1, "unit": "slices"},
    {"product": "Breakfast Wrap", "ingredient": "Tomato Chutney", "quantity":15, "unit": "grams"},
    {"product": "Breakfast Wrap", "ingredient": "Scrambled Egg", "quantity":1, "unit": "pieces"},
    {"product": "Breakfast Wrap", "ingredient": "Hash Brown", "quantity":1, "unit": "pieces"},
    {"product": "Breakfast Wrap", "ingredient": "Pork Sausage", "quantity":1, "unit": "pieces"},
    {"product": "Breakfast Wrap", "ingredient": "Back Bacon", "quantity":1, "unit": "rashers"},
    {"product": "Buttd Mushrooms", "ingredient": "Sourdough Loaf", "quantity":1, "unit": "slices"},
    {"product": "Buttd Mushrooms", "ingredient": "Unsalted Butter", "quantity":10, "unit": "grams"},
    {"product": "Buttd Mushrooms", "ingredient": "Fried Egg", "quantity":1, "unit": "pieces"},
    {"product": "Buttd Mushrooms", "ingredient": "Wild Rocket", "quantity":5, "unit": "grams"},
    {"product": "Buttd Mushrooms", "ingredient": "Sliced Mushroom", "quantity":125, "unit": "grams"},
    {"product": "Buttd Mushrooms", "ingredient": "Parsley", "quantity":0.2, "unit": "grams"},
    {"product": "Cheese & Bean JP", "ingredient": "Large Baking Potato", "quantity":1, "unit": "pieces"},
    {"product": "Cheese & Bean JP", "ingredient": "Baked Beans", "quantity":80, "unit": "grams"},
    {"product": "Cheese & Bean JP", "ingredient": "Mature Grated Cheddar", "quantity":40, "unit": "grams"},
    {"product": "Cheese & Bean JP", "ingredient": "Babyleaf Salad", "quantity":15, "unit": "grams"},
    {"product": "Cheese & Bean JP", "ingredient": "Cherry Tomatoes", "quantity":1, "unit": "pieces"},
    {"product": "Cheese JP", "ingredient": "Large Baking Potato", "quantity": 1, "unit": "pieces"},
    {"product": "Cheese JP", "ingredient": "Mature Grated Cheddar", "quantity": 40, "unit": "grams"},
    {"product": "Cheese JP", "ingredient": "Babyleaf Salad", "quantity": 15, "unit": "grams"},
    {"product": "Cheese JP", "ingredient": "Cherry Tomatoes", "quantity": 1, "unit": "pieces"},
    {"product": "Chick Flatbread", "ingredient": "Greek Style Flatbread", "quantity": 1, "unit": "pieces"},
    {"product": "Chick Flatbread", "ingredient": "Chicken Burger Fillet", "quantity": 1, "unit": "pieces"},
    {"product": "Chick Flatbread", "ingredient": "Unsmoked Streaky Bacon", "quantity": 2, "unit": "rashers"},
    {"product": "Chick Flatbread", "ingredient": "Caesar Dressing", "quantity": 15, "unit": "grams"},
    {"product": "Chick Flatbread", "ingredient": "Little Gem Lettuce", "quantity": 20, "unit": "grams"},
    {"product": "Chick Flatbread", "ingredient": "Parmigiano Reggiano", "quantity": 10, "unit": "grams"},
    {"product": "Chicken Club", "ingredient": "White Loaf With Sourdough", "quantity": 3, "unit": "slices"},
    {"product": "Chicken Club", "ingredient": "Flamegrilled Cooked Chicken Breast", "quantity": 45, "unit": "grams"},
    {"product": "Chicken Club", "ingredient": "Light Mayonnaise", "quantity": 20, "unit": "grams"},
    {"product": "Chicken Club", "ingredient": "Unsmoked Streaky Bacon", "quantity": 2, "unit": "rashers"},
    {"product": "Chicken Club", "ingredient": "Little Gem Lettuce", "quantity": 2, "unit": "pieces"},
    {"product": "Chicken Club", "ingredient": "Salad Tomatoes", "quantity": 4, "unit": "slices"},
    {"product": "Chicken Club", "ingredient": "Tomato Chutney", "quantity": 20, "unit": "grams"},
    {"product": "Chicken Club", "ingredient": "Skin on Fries", "quantity": 200, "unit": "grams"},
    {"product": "Chicken Club", "ingredient": "Chip Seasoning", "quantity": 0.5, "unit": "grams"},
    {"product": "Chilli Carne JP", "ingredient": "Large Baking Potato", "quantity": 1, "unit": "pieces"},
    {"product": "Chilli Carne JP", "ingredient": "Chilli Con Carne", "quantity": 196, "unit": "grams"},
    {"product": "Chilli Carne JP", "ingredient": "Mature Grated Cheddar", "quantity": 40, "unit": "grams"},
    {"product": "Chilli Carne JP", "ingredient": "Babyleaf Salad", "quantity": 15, "unit": "grams"},
    {"product": "Chilli Carne JP", "ingredient": "Cherry Tomatoes", "quantity": 1, "unit": "pieces"},
    {"product": "Egg Bacon Brioch", "ingredient": "Brioche Bun", "quantity": 1, "unit": "pieces"},
    {"product": "Egg Bacon Brioch", "ingredient": "Fried Egg", "quantity": 1, "unit": "pieces"},
    {"product": "Egg Bacon Brioch", "ingredient": "Unsmoked Streaky Bacon", "quantity": 2, "unit": "rashers"},
    {"product": "Egg Bacon Brioch", "ingredient": "Wild Rocket", "quantity": 5, "unit": "grams"},
    {"product": "Egg Bacon Brioch", "ingredient": "Sweet Chilli Jam", "quantity": 10, "unit": "grams"},
    {"product": "Egg Bacon Brioch", "ingredient": "Fresh Cut Coriander", "quantity": 2, "unit": "grams"},
    {"product": "Egg Bacon Brioch", "ingredient": "Light Soft Cheese", "quantity": 35, "unit": "grams"},
    {"product": "Egg Bacon Brioch", "ingredient": "Crushed Chillies", "quantity": 0.5, "unit": "grams"},
    {"product": "Egg Bap", "ingredient": "Large White Bap", "quantity": 1, "unit": "pieces"},
    {"product": "Egg Bap", "ingredient": "Unsalted Butter", "quantity": 10, "unit": "grams"},
    {"product": "Egg Bap", "ingredient": "Fried Egg", "quantity": 2, "unit": "pieces"},
    {"product": "F.Eggs on Toast", "ingredient": "White Farmhouse Bread", "quantity": 2, "unit": "slices"},
    {"product": "F.Eggs on Toast", "ingredient": "Unsalted Butter", "quantity": 10, "unit": "grams"},
    {"product": "F.Eggs on Toast", "ingredient": "Fried Egg", "quantity": 2, "unit": "pieces"},
    {"product": "Festive Stack", "ingredient": "Ciabatta Roll", "quantity": 1, "unit": "pieces"},
    {"product": "Festive Stack", "ingredient": "Chicken Burger Fillet", "quantity": 1, "unit": "pieces"},
    {"product": "Festive Stack", "ingredient": "Unsmoked Streaky Bacon", "quantity": 2, "unit": "rashers"},
    {"product": "Festive Stack", "ingredient": "French Brie", "quantity": 50, "unit": "grams"},
    {"product": "Festive Stack", "ingredient": "Cranberry Sauce", "quantity": 10, "unit": "grams"},
    {"product": "Festive Stack", "ingredient": "Little Gem Lettuce", "quantity": 2, "unit": "pieces"},
    {"product": "Festive Stack", "ingredient": "Parmigiano Reggiano", "quantity": 10, "unit": "grams"},
    {"product": "Festive Stack", "ingredient": "Skin on Fries", "quantity": 200, "unit": "grams"},
    {"product": "Fried Egg", "ingredient": "Fried Egg", "quantity": 1, "unit": "pieces"},
    {"product": "Hash Brown", "ingredient": "Hash Brown", "quantity": 2, "unit": "pieces"},
    {"product": "Hash Brown Bites", "ingredient": "Hash Brown Bites", "quantity": 150, "unit": "grams"},
    {"product": "Little Avo Toast", "ingredient": "50/50 Medium Bread", "quantity": 1, "unit": "pieces"},
    {"product": "Little Avo Toast", "ingredient": "Avocado", "quantity": 0.5, "unit": "pieces"},
    {"product": "Little Avo Toast", "ingredient": "Lime", "quantity": 0.25, "unit": "pieces"},
    {"product": "Little Bean Toas", "ingredient": "50/50 Medium Bread", "quantity": 1, "unit": "pieces"},
    {"product": "Little Bean Toas", "ingredient": "Unsalted Butter", "quantity": 5, "unit": "grams"},
    {"product": "Little Bean Toas", "ingredient": "Baked Beans", "quantity": 80, "unit": "grams"},
    {"product": "Ltle Bfast Bacon", "ingredient": "Baked Beans", "quantity": 80, "unit": "grams"},
    {"product": "Ltle Bfast Bacon", "ingredient": "50/50 Medium Bread", "quantity": 1, "unit": "pieces"},
    {"product": "Ltle Bfast Bacon", "ingredient": "Scrambled Egg", "quantity": 1, "unit": "pieces"},
    {"product": "Ltle Bfast Bacon", "ingredient": "Back Bacon", "quantity": 1, "unit": "pieces"},
    {"product": "Ltle Bfast Saus", "ingredient": "Baked Beans", "quantity": 80, "unit": "grams"},
    {"product": "Ltle Bfast Saus", "ingredient": "Scrambled Egg", "quantity": 1, "unit": "pieces"},
    {"product": "Ltle Bfast Saus", "ingredient": "50/50 Medium Bread", "quantity": 1, "unit": "pieces"},
    {"product": "Ltle Bfast Saus", "ingredient": "Pork Sausage", "quantity": 1, "unit": "pieces"},
    {"product": "Mini Hash Browns", "ingredient": "Hash Brown Bites", "quantity": 150, "unit": "grams"},
    {"product": "P.Eggs on Toast", "ingredient": "White Farmhouse Bread", "quantity": 2, "unit": "slices"},
    {"product": "P.Eggs on Toast", "ingredient": "Unsalted Butter", "quantity": 10, "unit": "grams"},
    {"product": "P.Eggs on Toast", "ingredient": "Poached Egg", "quantity": 2, "unit": "pieces"},
    {"product": "Poached Egg", "ingredient": "Poached Egg", "quantity": 1, "unit": "pieces"},
    {"product": "Posh Beans", "ingredient": "Sourdough Loaf", "quantity": 1, "unit": "slices"},
    {"product": "Posh Beans", "ingredient": "Five Beans in Tomato Sauce", "quantity": 200, "unit": "grams"},
    {"product": "Posh Beans", "ingredient": "BBQ Sauce", "quantity": 15, "unit": "grams"},
    {"product": "Posh Beans", "ingredient": "Poached Egg", "quantity": 1, "unit": "pieces"},
    {"product": "Posh Beans", "ingredient": "Fresh Cut Coriander", "quantity": 1, "unit": "grams"},
    {"product": "Roll & Butter", "ingredient": "Large White Bap", "quantity": 1, "unit": "pieces"},
    {"product": "S.Eggs on Toast", "ingredient": "White Farmhouse Bread", "quantity": 2, "unit": "pieces"},
    {"product": "S.Eggs on Toast", "ingredient": "Scrambled Egg", "quantity": 2, "unit": "pieces"},
    {"product": "S.Eggs on Toast", "ingredient": "Unsalted Butter", "quantity": 10, "unit": "grams"},
    {"product": "Sausage", "ingredient": "Pork Sausage", "quantity": 1, "unit": "pieces"},
    {"product": "Sausage Bap", "ingredient": "Pork Sausage", "quantity": 2, "unit": "pieces"},
    {"product": "Sausage Bap", "ingredient": "Large White Bap", "quantity": 1, "unit": "pieces"},
    {"product": "Sausage Bap", "ingredient": "Unsalted Butter", "quantity": 10, "unit": "grams"},
    {"product": "Scrambled Egg", "ingredient": "Scrambled Egg", "quantity": 1, "unit": "pieces"},
    {"product": "Scrambled Egg", "ingredient": "Semi Skimmed Milk", "quantity": 20, "unit": "grams"},
    {"product": "Streaky Bacon", "ingredient": "Unsmoked Streaky Bacon", "quantity": 1, "unit": "rashers"},
    {"product": "Tattie Scone", "ingredient": "Tattie Scone", "quantity": 1, "unit": "pieces"},
    {"product": "The Breakfast", "ingredient": "Baked Beans", "quantity": 80, "unit": "grams"},
    {"product": "The Breakfast", "ingredient": "Pork Sausage", "quantity": 1, "unit": "pieces"},
    {"product": "The Breakfast", "ingredient": "Back Bacon", "quantity": 1, "unit": "rashers"},
    {"product": "The Breakfast", "ingredient": "Fried Egg", "quantity": 1, "unit": "pieces"},
    {"product": "The Breakfast", "ingredient": "Hash Brown", "quantity": 2, "unit": "pieces"},
    {"product": "The Breakfast", "ingredient": "Tattie Scone", "quantity": 1, "unit": "pieces"},
    {"product": "Toasted Teacake", "ingredient": "Toasted Teacake", "quantity": 1, "unit": "pieces"},
    {"product": "Tuna JP", "ingredient": "Large Baking Potato", "quantity": 1, "unit": "pieces"},
    {"product": "Tuna JP", "ingredient": "Tuna Mayo Mix", "quantity": 80, "unit": "grams"},
    {"product": "Tuna JP", "ingredient": "Babyleaf Salad", "quantity": 15, "unit": "grams"},
    {"product": "Tuna JP", "ingredient": "Cherry Tomatoes", "quantity": 1, "unit": "pieces"},
    {"product": "Tuna Mayo Mix", "ingredient": "Tuna", "quantity": 80, "unit": "grams"},
    {"product": "Tuna Mayo Mix", "ingredient": "Spring Onions", "quantity": 1, "unit": "pieces"},
    {"product": "Tuna Mayo Mix", "ingredient": "Light Mayonnaise", "quantity": 40, "unit": "grams"},
    {"product": "Tuna Melt Panini", "ingredient": "Panini", "quantity": 2, "unit": "slices"},
    {"product": "Tuna Melt Panini", "ingredient": "Mature Grated Cheddar", "quantity": 32.5, "unit": "grams"},
    {"product": "Tuna Melt Panini", "ingredient": "Tuna Mayo Mix", "quantity": 80, "unit": "grams"},
    {"product": "Tuna Panini", "ingredient": "Panini", "quantity": 2, "unit": "slices"},
    {"product": "Tuna Panini", "ingredient": "Mature Grated Cheddar", "quantity": 32.5, "unit": "grams"},
    {"product": "Tuna Panini", "ingredient": "Tuna Mayo Mix", "quantity": 80, "unit": "grams"},
    {"product": "Tuna Toastie", "ingredient": "Sourdough Loaf", "quantity": 2, "unit": "slices"},
    {"product": "Tuna Toastie", "ingredient": "Mature Grated Cheddar", "quantity": 32.5, "unit": "grams"},
    {"product": "Tuna Toastie", "ingredient": "Grated Mozzarella", "quantity": 12.5, "unit": "grams"},
    {"product": "Tuna Toastie", "ingredient": "Bechamel", "quantity": 25, "unit": "grams"},
    {"product": "Tuna Toastie", "ingredient": "Tuna Mayo Mix", "quantity": 25, "unit": "grams"},
    {"product": "Veg Sausage Bap", "ingredient": "Large White Bap", "quantity": 1, "unit": "pieces"},
    {"product": "Veg Sausage Bap", "ingredient": "Unsalted Butter", "quantity": 10, "unit": "grams"},
    {"product": "Veg Sausage Bap", "ingredient": "Vegan Sausages", "quantity": 2, "unit": "pieces"},
    {"product": "Vegan Breakfast", "ingredient": "Baked Beans", "quantity": 80, "unit": "grams"},
    {"product": "Vegan Breakfast", "ingredient": "Avocado", "quantity": 0.5, "unit": "pieces"},
    {"product": "Vegan Breakfast", "ingredient": "Salad Tomato", "quantity": 0.5, "unit": "pieces"},
    {"product": "Vegan Breakfast", "ingredient": "Large Flat Mushrooms", "quantity": 1, "unit": "pieces"},
    {"product": "Vegan Breakfast", "ingredient": "Multiseed Bread", "quantity": 1, "unit": "slices"},
    {"product": "Vegan Breakfast", "ingredient": "Hash Brown", "quantity": 1, "unit": "pieces"},
    {"product": "Vegan Breakfast", "ingredient": "Vegan Sausages", "quantity": 2, "unit": "pieces"},
    {"product": "Vegan Breakfast", "ingredient": "Lime", "quantity": 0.25, "unit": "pieces"},
    {"product": "Vegan Sausage", "ingredient": "Vegan Sausage", "quantity": 1, "unit": "pieces"},
    {"product": "Veggie Bap", "ingredient": "Large White Bap", "quantity": 1, "unit": "pieces"},
    {"product": "Veggie Bap", "ingredient": "Unsalted Butter", "quantity": 10, "unit": "grams"},
    {"product": "Veggie Bap", "ingredient": "Vegan Sausages", "quantity": 2, "unit": "pieces"},
    {"product": "Veggie Breakfast", "ingredient": "Baked Beans", "quantity": 80, "unit": "grams"},
    {"product": "Veggie Breakfast", "ingredient": "Vegan Sausages", "quantity": 2, "unit": "pieces"},
    {"product": "Veggie Breakfast", "ingredient": "Fried Egg", "quantity": 1, "unit": "pieces"},
    {"product": "Veggie Breakfast", "ingredient": "Hash Brown", "quantity": 2, "unit": "pieces"},
    {"product": "Veggie Breakfast", "ingredient": "Tattie Scone", "quantity": 1, "unit": "pieces"},
    {"product": "Bakery", "ingredient": "Bakery", "quantity": 1, "unit": "pieces"},
    {"product": "White Toast Bread", "ingredient": "White Farmhouse Bread", "quantity": 2, "unit": "pieces"},
    {"product": "Brown Toast Bread", "ingredient": "Brown Farmhouse Bread", "quantity": 2, "unit": "pieces"},
    {"product": "Porridge", "ingredient": "Porridge Pot", "quantity": 1, "unit": "pieces"},
    {"product": "Sourdough Toast Bread", "ingredient": "Sourdough Loaf", "quantity": 2, "unit": "pieces"},
    {"product": "Multiseed Toast Bread", "ingredient": "Multiseed Bread", "quantity": 2, "unit": "pieces"},
    {"product": "Little Egg Toast", "ingredient": "50/50 Medium Bread", "quantity": 1, "unit": "pieces"},
    {"product": "Little Egg Toast", "ingredient": "Fried Egg", "quantity": 1, "unit": "pieces"},
    {"product": "Extra Beans", "ingredient": "Baked Beans", "quantity": 80, "unit": "grams"},
])














